# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0012_auto_20170725_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='nitg',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'TNO/NITG nummer'),
        ),
        migrations.AlterUniqueTogether(
            name='well',
            unique_together=set([('nitg', 'name')]),
        ),
    ]
