# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0013_auto_20170905_1215'),
        ('meetnet', '0016_auto_20170926_1046'),
    ]

    operations = [
    ]
