# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0017_merge_20171011_1656'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='handpeiling',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='loggerstat',
            name='max',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loggerstat',
            name='min',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loggerstat',
            name='p10',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loggerstat',
            name='p50',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loggerstat',
            name='p90',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loggerstat',
            name='std',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
