# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0018_auto_20171024_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='huisnummer',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
