# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0021_auto_20171031_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=b'fotos'),
        ),
    ]
