# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0022_auto_20171031_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handpeiling',
            options={'verbose_name': 'Handpeiling', 'verbose_name_plural': 'Handpeilingen'},
        ),
        migrations.AlterModelOptions(
            name='loggerpos',
            options={'ordering': ['start_date', 'logger'], 'verbose_name': 'LoggerInstallation'},
        ),
        migrations.AlterModelOptions(
            name='meteodata',
            options={'verbose_name': 'meteo', 'verbose_name_plural': 'Meteo'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'network', 'verbose_name_plural': 'networks'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['well', 'nr'], 'verbose_name': 'screen', 'verbose_name_plural': 'screens'},
        ),
        migrations.AlterModelOptions(
            name='well',
            options={'ordering': ['nitg', 'name'], 'verbose_name': 'well', 'verbose_name_plural': 'wells'},
        ),
        migrations.AddField(
            model_name='handpeiling',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meetnet.Screen', verbose_name='screen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datalogger',
            name='serial',
            field=models.CharField(max_length=50, unique=True, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='handpeiling',
            name='refpnt',
            field=models.CharField(choices=[(b'bkb', 'Top of casing'), (b'nap', 'NAP')], default=b'bkb', max_length=4, verbose_name='reference point'),
        ),
        migrations.AlterField(
            model_name='loggerpos',
            name='depth',
            field=models.FloatField(blank=True, help_text='length of cable in meter', null=True, verbose_name='cable length'),
        ),
        migrations.AlterField(
            model_name='loggerpos',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Stopping time of datalogger', null=True, verbose_name='stop'),
        ),
        migrations.AlterField(
            model_name='loggerpos',
            name='refpnt',
            field=models.FloatField(blank=True, help_text='Reference point in meter wrt NAP', null=True, verbose_name='reference point'),
        ),
        migrations.AlterField(
            model_name='loggerpos',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='loggerpos',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetnet.Screen', verbose_name='screen'),
        ),
        migrations.AlterField(
            model_name='loggerpos',
            name='start_date',
            field=models.DateTimeField(help_text='Start of datalogger', verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='baro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='well_baro', to='data.Series', verbose_name='air pressure'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='neerslag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='well_p', to='data.Series', verbose_name='precipitation'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='temperatuur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='well_temp', to='data.Series', verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='verdamping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='well_ev24', to='data.Series', verbose_name='evaporation'),
        ),
        migrations.AlterField(
            model_name='meteodata',
            name='well',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meteo', to='meetnet.Well', verbose_name='well'),
        ),
        migrations.AlterField(
            model_name='network',
            name='bound',
            field=models.URLField(blank=True, help_text='url of kml file of network boundary', verbose_name=b'grens'),
        ),
        migrations.AlterField(
            model_name='network',
            name='homepage',
            field=models.URLField(blank=True, help_text='website of netork administrator'),
        ),
        migrations.AlterField(
            model_name='network',
            name='last_round',
            field=models.DateField(blank=True, null=True, verbose_name='last measuring round'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='network',
            name='next_round',
            field=models.DateField(blank=True, null=True, verbose_name='next measuring round'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='bottom',
            field=models.FloatField(blank=True, help_text='bottom of screen in meters below the surface', null=True, verbose_name='bottom of screen'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='chart',
            field=models.ImageField(blank=True, null=True, upload_to=b'charts', verbose_name='chart'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='density',
            field=models.FloatField(default=1000.0, help_text='density of the water in observation tube (kg/m3)', verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='depth',
            field=models.FloatField(blank=True, help_text='depth of pipe in meters below the surface', null=True, verbose_name='depth'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='diameter',
            field=models.FloatField(blank=True, default=32, help_text='diameter in mm (default = 32 mm)', null=True, verbose_name='diameter'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='material',
            field=models.CharField(blank=True, choices=[(b'pvc', 'PVC'), (b'hdpe', 'HDPE'), (b'ss', 'SS'), (b'ms', 'steel')], default=b'pvc', max_length=10, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='nr',
            field=models.IntegerField(default=1, verbose_name='screen number'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='refpnt',
            field=models.FloatField(blank=True, help_text='top of casing in m wrt NAP', null=True, verbose_name='top of casing'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='top',
            field=models.FloatField(blank=True, help_text='top of screen in meters below the surface', null=True, verbose_name='top of screen'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetnet.Well', verbose_name='well'),
        ),
        migrations.AlterField(
            model_name='well',
            name='ahn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AHN surface level'),
        ),
        migrations.AlterField(
            model_name='well',
            name='bro',
            field=models.CharField(blank=True, max_length=50, verbose_name='BRO id'),
        ),
        migrations.AlterField(
            model_name='well',
            name='chart',
            field=models.ImageField(blank=True, null=True, upload_to=b'charts', verbose_name='chart'),
        ),
        migrations.AlterField(
            model_name='well',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of construction'),
        ),
        migrations.AlterField(
            model_name='well',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='well',
            name='g',
            field=models.FloatField(default=9.80665, help_text='gravitational acceleration in m/s2', verbose_name='gravitational acceleration'),
        ),
        migrations.AlterField(
            model_name='well',
            name='huisnummer',
            field=models.CharField(blank=True, max_length=12, verbose_name='house number'),
        ),
        migrations.AlterField(
            model_name='well',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='location in rijksdriehoeksstelsel coordinates', srid=28992, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='well',
            name='log',
            field=models.ImageField(blank=True, null=True, upload_to=b'logs', verbose_name="driller's log"),
        ),
        migrations.AlterField(
            model_name='well',
            name='maaiveld',
            field=models.FloatField(blank=True, help_text='surface level in meter wrt NAP', null=True, verbose_name='surface level'),
        ),
        migrations.AlterField(
            model_name='well',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='well',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetnet.Network', verbose_name='network'),
        ),
        migrations.AlterField(
            model_name='well',
            name='nitg',
            field=models.CharField(blank=True, max_length=50, verbose_name='TNO/NITG identification'),
        ),
        migrations.AlterField(
            model_name='well',
            name='plaats',
            field=models.CharField(blank=True, max_length=60, verbose_name='locality'),
        ),
        migrations.AlterField(
            model_name='well',
            name='postcode',
            field=models.CharField(blank=True, max_length=8, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='well',
            name='straat',
            field=models.CharField(blank=True, max_length=60, verbose_name='street name'),
        ),
    ]
