# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 21:54
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0023_auto_20171120_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='well',
            options={'ordering': ['name', 'nitg'], 'verbose_name': 'well', 'verbose_name_plural': 'wells'},
        ),
        migrations.AlterField(
            model_name='well',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Location in longitude/latitude coordinates', srid=4326, verbose_name='location'),
        ),
        migrations.AlterUniqueTogether(
            name='well',
            unique_together=set([('name', 'nitg')]),
        ),
    ]
