# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 00:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0026_auto_20171228_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='wgs',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Location in longitude/latitude coordinates', null=True, srid=4326, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='well',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Location in longitude/latitude coordinates', srid=28992, verbose_name='location'),
        ),
    ]
