# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 00:25
from __future__ import unicode_literals

from django.db import migrations
from acacia.data.util import WGS84

def copylocation(apps, schema_editor):
    model = apps.get_model('meetnet', 'Well')
    for m in model.objects.all():
        m.wgs = m.location.clone()
        m.wgs.transform(WGS84)
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0027_auto_20180105_0119'),
    ]

    operations = [
        migrations.RunPython(copylocation),
    ]
