# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0028_auto_20180105_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='location',
        ),
    ]
