# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0031_auto_20181114_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='group')),
                ('screen', models.ManyToManyField(to='meetnet.Screen', verbose_name='screen')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
