# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-08 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0032_screengroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screengroup',
            name='screen',
        ),
        migrations.AddField(
            model_name='screen',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='group'),
        ),
        migrations.DeleteModel(
            name='ScreenGroup',
        ),
    ]
