# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-26 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0033_auto_20190508_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='display_name',
            field=models.CharField(choices=[(b'name', 'name'), (b'nitg', 'nitg')], default=b'name', max_length=4, verbose_name='displayname'),
        ),
    ]
