# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0034_network_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='display_name',
            field=models.CharField(choices=[(b'name', 'well name'), (b'nitg', 'NITG-code')], default=b'name', help_text='display well names with NITG code or use custom names', max_length=4, verbose_name='displayname'),
        ),
    ]
