# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0036_auto_20190811_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handpeilingen',
            name='screen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meetnet.Screen', verbose_name='screen'),
        ),
    ]
