# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0037_auto_20190811_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='login_required'),
        ),
    ]
