# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-17 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0038_network_login_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='bro',
            new_name='broid',
        ),
    ]
