# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0039_auto_20191117_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='material',
            field=models.CharField(blank=True, choices=[(b'pvc', 'PVC'), (b'hdpe', 'HDPE'), (b'ss', 'stainless steel'), (b'ms', 'steel')], default=b'pvc', max_length=10, verbose_name='material'),
        ),
    ]
