# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0040_auto_20191124_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggerpos',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start of datalogger', null=True, verbose_name='start'),
        ),
    ]
