# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-02 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20191203_0010'),
        ('meetnet', '0041_auto_20191202_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompoundSeries',
            fields=[
                ('series_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.Series')),
                ('more', models.ManyToManyField(related_name='more', to='data.Series')),
            ],
            options={
                'abstract': False,
            },
            bases=('data.series',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
