# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-06 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_auto_20200206_2112'),
        ('meetnet', '0042_compoundseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggerpos',
            name='files',
            field=models.ManyToManyField(help_text='related source files', to='data.SourceFile', verbose_name='source files'),
        ),
    ]
