# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0043_loggerpos_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalogger',
            name='model',
            field=models.CharField(choices=[(b'micro', b'Micro-Diver'), (b'3', b'TD-Diver'), (b'ctd', b'CTD-Diver'), (b'16', b'Cera-Diver'), (b'14', b'Mini-Diver'), (b'baro', b'Baro-Diver'), (b'etd', b'ElliTrack-D'), (b'etd2', b'ElliTrack-D2'), (b'blik', b'Bliksensing')], default=b'14', max_length=50, verbose_name='type'),
        ),
    ]
