# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 14:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeerslagStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('naam', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=28992)),
            ],
            options={
                'ordering': ('naam',),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.IntegerField()),
                ('naam', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=28992)),
            ],
            options={
                'ordering': ('naam',),
            },
        ),
    ]
