# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 15:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knmi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neerslagstation',
            name='wgs',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='station',
            name='wgs',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
