# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 22:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knmi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neerslagstation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
