# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knmi', '0002_auto_20171220_1131'),
        ('knmi', '0002_auto_20171222_1116'),
    ]

    operations = [
    ]
