# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 15:48
from __future__ import unicode_literals

from django.db import migrations
from acacia.data.util import WGS84

def copylocation(apps, schema_editor):
    model = apps.get_model('knmi', 'Station')
    for m in model.objects.all():
        m.wgs = m.location.clone()
        m.wgs.transform(WGS84)
        m.save()

    model = apps.get_model('knmi', 'NeerslagStation')
    for m in model.objects.all():
        m.wgs = m.location.clone()
        m.wgs.transform(WGS84)
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('knmi', '0002_auto_20180104_1648'),
    ]

    operations = [
        migrations.RunPython(copylocation),
    ]
