# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knmi', '0003_auto_20180104_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neerslagstation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='station',
            name='location',
        ),
    ]
