# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knmi', '0004_auto_20180104_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neerslagstation',
            old_name='wgs',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='wgs',
            new_name='location',
        ),
    ]
