# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-01 07:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('topo_2561_field', models.IntegerField()),
                ('topo_25611', models.IntegerField()),
                ('bladnaam', models.CharField(max_length=20)),
                ('nr', models.IntegerField()),
                ('ltr', models.CharField(max_length=1)),
                ('district', models.CharField(max_length=2)),
                ('blad', models.CharField(max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=28992)),
            ],
        ),
    ]
