# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-25 10:17
from __future__ import unicode_literals

import acacia.meetnet.bro.models
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetnet', '0040_auto_20191124_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes',
            },
        ),
        migrations.CreateModel(
            name='CodeSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSpace', models.CharField(max_length=40, verbose_name='codeSpace')),
                ('description', models.CharField(blank=True, max_length=40, null=True, verbose_name='Description')),
                ('default_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bro.Code', verbose_name='default code')),
            ],
            options={
                'verbose_name': 'Code space',
                'verbose_name_plural': 'Code spaces',
            },
        ),
        migrations.CreateModel(
            name='GroundwaterMonitoringWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectIdAccountableParty', models.CharField(max_length=100, verbose_name='ObjectID')),
                ('numberOfMonitoringTubes', models.PositiveIntegerField(default=1, verbose_name='Aantal monitoringbuizen')),
                ('groundLevelStable', models.NullBooleanField(verbose_name='Maaiveld stabiel')),
                ('wellStability', models.NullBooleanField(max_length=16, verbose_name='Putstabiliteit')),
                ('nitgCode', models.CharField(blank=True, max_length=8, null=True, verbose_name='NITG code')),
                ('mapSheetCode', models.CharField(blank=True, max_length=3, null=True, verbose_name='Kaartblad')),
                ('owner', models.CharField(help_text='KVK-nummer van de eigenaar', max_length=8, validators=[django.core.validators.RegexValidator(message='Illegal chamber of commerce number', regex='\\d{8}')], verbose_name='Eigenaar')),
                ('maintenanceResponsibleParty', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Illegal chamber of commerce number', regex='\\d{8}')], verbose_name='Onderhoudende instantie')),
                ('wellConstructionDate', models.DateField()),
                ('deliveredLocation', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinaten')),
                ('deliveredVerticalPosition', models.FloatField(verbose_name='Maaiveld')),
                ('constructionStandard', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kwaliteitsnorm inrichting')),
                ('deliveryContext', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kader aanlevering')),
                ('groundLevelPositioningMethod', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Maaiveld positiebepaling')),
                ('horizontalPositioningMethod', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Methode locatiebepaling')),
                ('initialFunction', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Initi\xeble functie')),
                ('well', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro', to='meetnet.Well')),
                ('wellHeadProtector', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Beschermconstructie')),
            ],
        ),
        migrations.CreateModel(
            name='MapSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('topo_2561_field', models.IntegerField()),
                ('topo_25611', models.IntegerField()),
                ('bladnaam', models.CharField(max_length=20)),
                ('nr', models.IntegerField()),
                ('ltr', models.CharField(max_length=1)),
                ('district', models.CharField(max_length=2)),
                ('blad', models.CharField(max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=28992)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tubeNumber', models.PositiveSmallIntegerField(default=1)),
                ('artesianWellCapPresent', models.NullBooleanField(verbose_name='Drukdop')),
                ('sedimentSumpPresent', models.NullBooleanField(verbose_name='Zandvang')),
                ('numberOfGeoOhmCables', models.PositiveSmallIntegerField(default=0)),
                ('tubeTopDiameter', models.FloatField(verbose_name='Diameter')),
                ('variableDiameter', models.BooleanField(default=False, verbose_name='Variabele diameter')),
                ('tubeTopPosition', models.FloatField(verbose_name='Bovenkant buis')),
                ('screenLength', models.FloatField(verbose_name='Filterlengte')),
                ('plainTubePart', models.FloatField(verbose_name='Lengte stijgbuis')),
                ('sedimentSump', models.FloatField(default=0, verbose_name='Lengte zandvang')),
                ('screen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro', to='meetnet.Screen')),
                ('sockMaterial', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kousmateriaal')),
                ('tubeMaterial', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Buismateriaal')),
                ('tubePackingMaterial', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Aanvul materiaal')),
                ('tubeStatus', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Status')),
                ('tubeTopPositioningMethod', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Methode positiebepaling bovenkant buis')),
                ('tubeType', acacia.meetnet.bro.models.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Buistype')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='codeSpace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bro.CodeSpace'),
        ),
    ]
