# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-02 23:09
from __future__ import unicode_literals

import acacia.meetnet.bro.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestReference', models.CharField(max_length=100, verbose_name='requestReference')),
                ('deliveryAccountableParty', models.CharField(help_text='KVK nummer van bronhouder', max_length=8, validators=[django.core.validators.RegexValidator(message='Illegal chamber of commerce number', regex=b'\\d{8}')], verbose_name='deliveryAccountableParty')),
                ('underPrivilege', models.NullBooleanField(verbose_name='Onder voorrecht')),
                ('qualityRegime', acacia.meetnet.bro.fields.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kwaliteitsregime')),
            ],
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='groundLevelStable',
            field=models.NullBooleanField(verbose_name='Ground level stable'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='initialFunction',
            field=acacia.meetnet.bro.fields.CodeField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Initial function'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='mapSheetCode',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Mapsheet'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='numberOfMonitoringTubes',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of monitoring tubes'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='owner',
            field=models.CharField(help_text='KVK-nummer van de eigenaar', max_length=8, validators=[django.core.validators.RegexValidator(message='Illegal chamber of commerce number', regex=b'\\d{8}')], verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='wellStability',
            field=models.NullBooleanField(max_length=16, verbose_name='WellStability'),
        ),
    ]
