# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0039_auto_20191117_0103'),
        ('bro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSpace', models.CharField(max_length=40, verbose_name='codeSpace')),
                ('code', models.CharField(max_length=40, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='GroundwaterMonitoringWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groundLevelStable', models.NullBooleanField(default='onbekend', verbose_name='Maaiveld stabiel')),
                ('wellStability', models.NullBooleanField(default='onbekend', max_length=16, verbose_name='Putstabiliteit')),
                ('constructionStandard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kwaliteitsnorm inrichting')),
                ('deliveryContext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kader aanlevering')),
                ('initialFunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Initiele functie')),
                ('maintenanceResponsibleParty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Onderhoudende instantie')),
                ('well', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro', to='meetnet.Well')),
                ('wellHeadProtector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Beschermconstructie')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artesianWellCapPresent', models.NullBooleanField(verbose_name='Drukdop')),
                ('sedimentSumpPresent', models.NullBooleanField(verbose_name='Zandvang')),
                ('variableDiameter', models.BooleanField(default=False, verbose_name='Variabele diameter')),
                ('groundwaterMonitoringWell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bro.GroundwaterMonitoringWell', verbose_name='GroundwaterMonitoringWell')),
                ('screen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro', to='meetnet.Screen')),
                ('sockMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kousmateriaal')),
                ('tubePackingMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Aanvul materiaal')),
                ('tubeStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Status')),
                ('tubeTopPositioningMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Methode positiebepaling bovenkant buis')),
                ('tubeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Buistype')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together=set([('codeSpace', 'code')]),
        ),
    ]
