# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-07 13:19
from __future__ import unicode_literals

import acacia.meetnet.bro.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='qualityRegime',
            field=acacia.meetnet.bro.fields.CodeField(default='IMBRO/A', max_length=20, verbose_name='Kwaliteitsregime'),
        ),
    ]
