# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-19 22:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetnet', '0039_auto_20191117_0103'),
        ('bro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSpace', models.CharField(max_length=40, verbose_name='codeSpace')),
                ('code', models.CharField(max_length=40, verbose_name='code')),
                ('default_value', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroundwaterMonitoringWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectIdAccountableParty', models.CharField(max_length=100, verbose_name='ObjectID')),
                ('numberOfMonitoringTubes', models.PositiveIntegerField(default=1, verbose_name='Aantal monitoringbuizen')),
                ('groundLevelStable', models.NullBooleanField(default='onbekend', verbose_name='Maaiveld stabiel')),
                ('wellStability', models.NullBooleanField(default='onbekend', max_length=16, verbose_name='Putstabiliteit')),
                ('nitgCode', models.CharField(blank=True, max_length=8, null=True, verbose_name='NITG code')),
                ('mapSheetCode', models.CharField(blank=True, max_length=3, null=True, verbose_name='Kaartblad')),
                ('owner', models.CharField(help_text='KVK-nummer van de eigenaar', max_length=8, verbose_name='Eigenaar')),
                ('maintenanceResponsibleParty', models.CharField(blank=True, max_length=8, null=True, verbose_name='Onderhoudende instantie')),
                ('wellConstructionDate', models.DateField()),
                ('deliveredLocation', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordinaten')),
                ('deliveredVerticalPosition', models.FloatField(verbose_name='Maaiveld')),
                ('constructionStandard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kwaliteitsnorm inrichting')),
                ('deliveryContext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kader aanlevering')),
                ('groundLevelPositioningMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Maaiveld positiebepaling')),
                ('horizontalPositioningMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Methode locatiebepaling')),
                ('initialFunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Initi\xeble functie')),
                ('well', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro', to='meetnet.Well')),
                ('wellHeadProtector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Beschermconstructie')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tubeNumber', models.PositiveSmallIntegerField(default=1)),
                ('artesianWellCapPresent', models.NullBooleanField(verbose_name='Drukdop')),
                ('sedimentSumpPresent', models.NullBooleanField(verbose_name='Zandvang')),
                ('numberOfGeoOhmCables', models.PositiveSmallIntegerField(default=0)),
                ('tubeTopDiameter', models.FloatField(verbose_name='Diameter')),
                ('variableDiameter', models.BooleanField(default=False, verbose_name='Variabele diameter')),
                ('tubeTopPosition', models.FloatField(verbose_name='Bovenkant buis')),
                ('screenLength', models.FloatField(verbose_name='Filterlengte')),
                ('plainTubePart', models.FloatField(verbose_name='Lengte stijgbuis')),
                ('sedimentSump', models.FloatField(default=0, verbose_name='Lengte zandvang')),
                ('materialUsed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Buismateriaal')),
                ('screen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro', to='meetnet.Screen')),
                ('sockMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Kousmateriaal')),
                ('tubePackingMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Aanvul materiaal')),
                ('tubeStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Status')),
                ('tubeTopPositioningMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Methode positiebepaling bovenkant buis')),
                ('tubeType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Buistype')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together=set([('codeSpace', 'code')]),
        ),
    ]
