# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-04 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0002_auto_20191203_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groundwatermonitoringwell',
            old_name='deliveredLocation',
            new_name='location',
        ),
    ]
