# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-18 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0002_auto_20191118_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='initialFunction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bro.Code', verbose_name='Initi\xebleFunctie'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='maintenanceResponsibleParty',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Onderhoudende instantie'),
        ),
    ]
