# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-18 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0003_auto_20191118_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringtube',
            name='groundwaterMonitoringWell',
        ),
    ]
