# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-04 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0003_auto_20191204_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='gmw',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bro.GroundwaterMonitoringWell', verbose_name='GroundwaterMonitoringWell'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='requestReference',
            field=models.CharField(default='Verzoek voor put %s', max_length=100, verbose_name='requestReference'),
        ),
    ]
