# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-17 20:44
from __future__ import unicode_literals

import acacia.meetnet.bro.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bro', '0003_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwell',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwell',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='groundwatermonitoringwell',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoringtube',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoringtube',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='monitoringtube',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defaults',
            name='deliveryAccountableParty',
            field=models.CharField(help_text='KVK nummer van de bronhouder', max_length=8, validators=[django.core.validators.RegexValidator(message='Illegal chamber of commerce number', regex=b'\\d{8}')], verbose_name='deliveryAccountableParty'),
        ),
        migrations.AlterField(
            model_name='defaults',
            name='maintenanceResponsibleParty',
            field=models.CharField(blank=True, help_text=b'KVK-nummer van de onderhoudende instantie', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Illegal chamber of commerce number', regex=b'\\d{8}')], verbose_name='Onderhoudende instantie'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='groundLevelStable',
            field=acacia.meetnet.bro.fields.IndicationYesNoUnknownEnumeration(default='onbekend', max_length=20, verbose_name='Ground level stable'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='well',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro', to='meetnet.Well', verbose_name='well'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='wellStability',
            field=acacia.meetnet.bro.fields.IndicationYesNoUnknownEnumeration(default='onbekend', max_length=20, verbose_name='WellStability'),
        ),
        migrations.AlterField(
            model_name='monitoringtube',
            name='artesianWellCapPresent',
            field=acacia.meetnet.bro.fields.IndicationYesNoUnknownEnumeration(default='onbekend', max_length=20, verbose_name='ArtesianWellCapPresent'),
        ),
        migrations.AlterField(
            model_name='monitoringtube',
            name='numberOfGeoOhmCables',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='NumberOfGeoOhmCables'),
        ),
        migrations.AlterField(
            model_name='monitoringtube',
            name='screen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bro', to='meetnet.Screen', verbose_name='tube'),
        ),
        migrations.AlterField(
            model_name='monitoringtube',
            name='sedimentSumpPresent',
            field=acacia.meetnet.bro.fields.IndicationYesNoUnknownEnumeration(default='onbekend', max_length=20, verbose_name='SedimentSumpPresent'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='requestReference',
            field=models.CharField(blank=True, max_length=100, verbose_name='requestReference'),
        ),
        migrations.CreateModel(
            name='GMW_Construction',
            fields=[
                ('sourcedocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bro.SourceDocument')),
                ('gmw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bro.GroundwaterMonitoringWell')),
            ],
            bases=('bro.sourcedocument',),
        ),
    ]
