# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-04 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0004_auto_20191204_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groundwatermonitoringwell',
            options={'verbose_name': 'GroundwaterMonitoringWell', 'verbose_name_plural': 'GroundwaterMonitoringWells'},
        ),
        migrations.AlterModelOptions(
            name='monitoringtube',
            options={'verbose_name': 'MonitoringTube', 'verbose_name_plural': 'MonitoringTubes'},
        ),
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'verbose_name': 'RegistrationRequest', 'verbose_name_plural': 'RegistrationRequests'},
        ),
        migrations.RenameField(
            model_name='monitoringtube',
            old_name='plainTubePart',
            new_name='plainTubePartLength',
        ),
    ]
