# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-19 13:17
from __future__ import unicode_literals

import acacia.meetnet.bro.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0004_auto_20191217_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringtube',
            name='variableDiameter',
            field=acacia.meetnet.bro.fields.IndicationYesNoEnumeration(default='nee', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='underPrivilege',
            field=acacia.meetnet.bro.fields.IndicationYesNoEnumeration(default='ja', max_length=20),
        ),
    ]
