# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-19 13:34
from __future__ import unicode_literals

from django.db import migrations

def update(apps, schema_editor):
    apps.get_model('bro', 'RegistrationRequest').objects.filter(underPrivilege='onbekend').update(underPrivilege='ja')
    apps.get_model('bro', 'MonitoringTube').objects.exclude(variableDiameter='ja').update(variableDiameter='nee')

def reverse():
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0005_auto_20191219_1417'),
    ]

    operations = [
        migrations.RunPython(update, reverse)
    ]
