# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-04 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0005_auto_20191204_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groundwatermonitoringwell',
            old_name='deliveredVerticalPosition',
            new_name='groundLevelPosition',
        ),
    ]
