# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-05-18 08:00
from __future__ import unicode_literals

import acacia.meetnet.bro.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0006_auto_20191219_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='groundLevelStable',
            field=acacia.meetnet.bro.fields.IndicationYesNoUnknownEnumeration(max_length=20, verbose_name='Ground level stable'),
        ),
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='wellStability',
            field=acacia.meetnet.bro.fields.IndicationYesNoUnknownEnumeration(max_length=20, verbose_name='WellStability'),
        ),
        migrations.AlterField(
            model_name='monitoringtube',
            name='artesianWellCapPresent',
            field=acacia.meetnet.bro.fields.IndicationYesNoUnknownEnumeration(max_length=20, verbose_name='ArtesianWellCapPresent'),
        ),
        migrations.AlterField(
            model_name='monitoringtube',
            name='sedimentSumpPresent',
            field=acacia.meetnet.bro.fields.IndicationYesNoUnknownEnumeration(max_length=20, verbose_name='SedimentSumpPresent'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='qualityRegime',
            field=acacia.meetnet.bro.fields.CodeField(max_length=20, verbose_name='Kwaliteitsregime'),
        ),
    ]
