# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 12:27
from __future__ import unicode_literals

import acacia.meetnet.bro.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0007_auto_20200518_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundwatermonitoringwell',
            name='wellConstructionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='qualityRegime',
            field=acacia.meetnet.bro.fields.CodeField(default='IMBRO/A', max_length=20, verbose_name='Kwaliteitsregime'),
        ),
    ]
