# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0008_auto_20200615_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringtube',
            name='tubeTopDiameter',
            field=models.FloatField(null=True, verbose_name='Diameter'),
        ),
    ]
