# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-23 13:57
from __future__ import unicode_literals

import acacia.meetnet.bro.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bro', '0009_auto_20200615_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='qualityRegime',
            field=acacia.meetnet.bro.fields.CodeField(max_length=20, verbose_name='Kwaliteitsregime'),
        ),
    ]
