# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahn', '0002_auto_20170329_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahn',
            name='layer',
            field=models.CharField(max_length=50, verbose_name='layer'),
        ),
        migrations.AlterField(
            model_name='ahn',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ahn',
            name='resolution',
            field=models.FloatField(verbose_name='resolution'),
        ),
    ]
