# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 21:52
from __future__ import unicode_literals

from django.db import migrations
from acacia.data.util import WGS84

def copylocation(apps, schema_editor):
    model = apps.get_model('data', 'ProjectLocatie')
    for m in model.objects.all():
        m.wgs = m.location.clone()
        m.wgs.transform(WGS84)
        m.save()

    model = apps.get_model('data', 'MeetLocatie')
    for m in model.objects.all():
        m.wgs = m.location.clone()
        m.wgs.transform(WGS84)
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20171219_2251'),
    ]

    operations = [
        migrations.RunPython(copylocation),
    ]
