# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 21:57
from __future__ import unicode_literals

from django.db import migrations
from acacia.data.util import setWGS84

def reproject_all(apps, schema_editor):
    model = apps.get_model('data', 'ProjectLocatie')
    for obj in model.objects.all():
        setWGS84(obj)
    model = apps.get_model('data', 'MeetLocatie')
    for obj in model.objects.all():
        setWGS84(obj)
     
class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_auto_20171218_2254'),
    ]

    operations = [
        migrations.RunPython(reproject_all),
    ]
