# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_auto_20171219_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetlocatie',
            old_name='wgs',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='projectlocatie',
            old_name='wgs',
            new_name='location',
        ),
    ]
