# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_auto_20171218_1626'),
        ('data', '0034_auto_20171219_2259'),
    ]

    operations = [
    ]
