# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_auto_20171222_1116'),
        ('data', '0036_auto_20171221_1420'),
    ]

    operations = [
    ]
