# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-01-22 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20210122_1330'),
        ('data', '0045_auto_20200615_1427'),
    ]

    operations = [
    ]
