# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-01-23 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_merge_20210122_1337'),
        ('data', '0046_auto_20210122_1318'),
    ]

    operations = [
    ]
