# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-14 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0038_auto_20180616_1608'),
        ('validation', '0031_auto_20170928_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'filter',
                'verbose_name_plural': 'filters',
            },
        ),
        migrations.CreateModel(
            name='FilterOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.Filter')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validation.BaseRule')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Filter Regel',
                'verbose_name_plural': 'Filter Regels',
            },
        ),
        migrations.AddField(
            model_name='filter',
            name='rules',
            field=models.ManyToManyField(related_name='filters', through='validation.FilterOrder', to='validation.BaseRule', verbose_name=b'regels'),
        ),
        migrations.AddField(
            model_name='filter',
            name='series',
            field=models.ManyToManyField(to='data.Series', verbose_name=b'tijdreeksen'),
        ),
    ]
