# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-25 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0033_auto_20190123_1058'),
        ('validation', '0033_auto_20190123_1134'),
    ]

    operations = [
    ]
