# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-30 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0035_maaiveldrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maaiveldrule',
            options={'verbose_name': 'Maaiveld'},
        ),
        migrations.RemoveField(
            model_name='maaiveldrule',
            name='well',
        ),
    ]
