# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0036_auto_20190731_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='result',
            name='valid',
            field=models.NullBooleanField(default=False),
        ),
    ]
